### ISSUE TITLE
Vulnerability Annotator does not publish when exception is thrown during scanning package file 

### ISSUE THREAD

**Issue by Ali-Amin** [project-alvarium/alvarium-sdk-java#122]
[The part of the annotator that executes](https://github.com/project-alvarium/alvarium-sdk-java/blob/d18f5aeadd83be1ce86cd70bf79a1cd42b2836e4/src/main/java/com/alvarium/annotators/VulnerabilityAnnotator.java#L64)
```java
Map<String, String> packages = getPackages(dir);
```
which is the method responsible for scanning the manifest/package file and returning a map of package IDs and versions, is not being checked for any exceptions being thrown, which is against the design agreed upon in #111 where the annotation should still be created but with `isSatisfied=false`.

**Comment by o-eissa** [comment]
Will adding the getPacakges method call in the try block as below handle the issue?
```java
        final String key = super.deriveHash(hash, data);

        String dir = ctx.getProperty(AnnotationType.VULNERABILITY.name(), String.class);
        
        List<String> vulnerabilities;
        boolean isSatisfied;
        String host = "";
        try{
            host = InetAddress.getLocalHost().getHostName();

            Map<String, String> packages = getPackages(dir);
            vulnerabilities = retrievePackagesVulnerabilities(packages);
            isSatisfied = vulnerabilities.isEmpty();
        } catch (UnknownHostException | AnnotatorException e) {
            isSatisfied = false;
            this.logger.error("Error during VulnerabilityAnnotator execution: ",e);
        }
```

**Comment by Ali-Amin** [comment]
> Will adding the getPacakges method call in the try block as below handle the issue?
> 
> ```java
>         final String key = super.deriveHash(hash, data);
> 
>         String dir = ctx.getProperty(AnnotationType.VULNERABILITY.name(), String.class);
>         
>         List<String> vulnerabilities;
>         boolean isSatisfied;
>         String host = "";
>         try{
>             host = InetAddress.getLocalHost().getHostName();
> 
>             Map<String, String> packages = getPackages(dir);
>             vulnerabilities = retrievePackagesVulnerabilities(packages);
>             isSatisfied = vulnerabilities.isEmpty();
>         } catch (UnknownHostException | AnnotatorException e) {
>             isSatisfied = false;
>             this.logger.error("Error during VulnerabilityAnnotator execution: ",e);
>         }
> ```

Yes, I believe so.
